---
title: "Final Project"
author: "Vasiliy Ostapenko (774 970 8)"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---
```{r setup, echo=FALSE, include=FALSE}
library(knitr)
library(tidyverse)
library(tidymodels)
library(corrplot)
library(fastDummies)
library(data.table)
library(ggridges)
library(vcd)
knitr::opts_chunk$set(fig.width=4, fig.height=3, 
                      warning=FALSE, message=FALSE)
options(digits=4)
set.seed(42)
```

## DATA
### Load Data
```{r}
DATA_FOLDER = "./data"
COMBINED_FNAME = file.path(DATA_FOLDER, "combined.csv")
df = read.csv(COMBINED_FNAME) %>%
  column_to_rownames("vaersId")
```

### Visualization
```{r}
# Plot 1
g1 = ggplot(df, aes(x=sex, y=age, fill=as.factor(recovered))) + 
  geom_boxplot()
g1
```
```{r}
# Plot 2
g2 = ggplot(df, aes(x=as.factor(region), y=nCovidVax, fill=as.factor(recovered))) +
  geom_violin()
g2
```
```{r}
# Plot 3
g3 = ggplot(df[!(df$otherMeds %in% c(0, 1)), ], aes(x=otherMeds, y=as.factor(recovered), fill=as.factor(recovered))) +
  geom_density_ridges() +
  theme_ridges()
g3
```
```{r}
# Plot 4
p4 = mosaic(~myocarditis+sex, data=df, shade=TRUE, legend=TRUE)
p4
```

### Categorical to Numeric Conversion
```{r}
df = fastDummies::dummy_cols(df, remove_first_dummy=TRUE, remove_selected_columns=TRUE)
```
```{r}
corrplot(cor(df[ , names(df) != "recovered_Y"]), 
         method="color", type="lower")
```
```{r}
df = df[ , !(colnames(df) %in% c("myocarditis"))] %>% copy()
df$recovered_Y = as.factor(df$recovered_Y)
```

### Data Split
```{r}
split = df %>%
  initial_split(prop=0.70, strata="recovered_Y")

train = training(split)
test = testing(split)
```
```{r}
folds = vfold_cv(train, v=3, strata="recovered_Y")
```

## MODELING
### Recipe
```{r}
rec = recipe(recovered_Y ~ ., data=train) %>%
  step_normalize(all_predictors())
```

### Models, Workflows, Parameters, CV
```{r, eval=FALSE}
# Logistic Regression
mod_glm = logistic_reg(penalty=tune(), mixture=tune()) %>%
  set_engine("glm") %>%
  set_mode("classification")

work_glm = workflow() %>%
  add_model(mod_glm) %>%
  add_recipe(rec)

grid_glm = grid_regular(penalty(), mixture(), levels=5)

tune_glm = work_glm %>%
  tune_grid(resamples=folds, grid=grid_glm, 
            metrics=metric_set(roc_auc, accuracy))

save(tune_glm, work_glm, file="./data/tune_glm.rda")
```
```{r}
load(file="./data/tune_glm.rda")
tune_glm %>% collect_metrics() %>% 
  select(-.estimator, -.config)
```

```{r, eval=TRUE}
# SVM
mod_svm = svm_poly(cost=tune(), degree=tune()) %>%
  set_engine("kernlab") %>%
  set_mode("classification")

work_svm = workflow() %>%
  add_model(mod_svm) %>%
  add_recipe(rec)

grid_svm = grid_regular(cost(), degree(), levels=2)

tune_svm = work_svm %>%
  tune_grid(resamples=folds, grid=grid_svm,
            metrics=metric_set(roc_auc, accuracy))

save(tune_svm, work_svm, file="./data/tune_svm.rda")
```
```{r}
load(file="./data/tune_svm.rda")
tune_svm %>% collect_metrics() %>%
  select(-.estimator, -.config)
```

```{r, eval=FALSE}
# Random Forest
mod_rf = rand_forest(min_n=tune(), mtry=tune()) %>%
  set_engine("ranger") %>%
  set_mode("classification")

work_rf = workflow() %>%
  add_model(mod_rf) %>%
  add_recipe(rec)

grid_rf = grid_regular(min_n(), mtry(range=c(1, 14)), levels=2)

tune_rf = work_rf %>%
  tune_grid(resamples=folds, grid=grid_rf,
            metrics=metric_set(roc_auc, accuracy))

save(tune_rf, work_rf, file="./data/tune_rf.rda")
```
```{r}
load(file="./data/tune_rf.rda")
tune_rf %>% collect_metrics() %>% 
  select(-.estimator, -.config)
```

```{r, eval=FALSE}
# Boosted Trees
mod_boost = boost_tree(min_n=tune(), learn_rate=tune(), mtry=tune()) %>%
  set_engine("xgboost") %>%
  set_mode("classification")

work_boost = workflow() %>%
  add_model(mod_boost) %>%
  add_recipe(rec)

grid_boost = grid_regular(min_n(), learn_rate(), mtry(range=c(1, 14)), levels=3)

tune_boost = work_boost %>%
  tune_grid(resamples=folds, grid=grid_boost, 
            metrics=metric_set(roc_auc, accuracy))

save(tune_boost, work_boost, file="./data/tune_boost.rda")
```
```{r}
load(file="./data/tune_boost.rda")
tune_boost %>% collect_metrics() %>% 
  select(-.estimator, -.config)
```

### Best Model Determination and Training
```{r, eval=TRUE}
tune_best = tune_rf %>%
  select_best("roc_auc")

work_final = work_rf %>%
  finalize_workflow(tune_best)

fit_best = work_final %>%
  fit(train)

save(fit_best, file="./data/fit_best.rda")
```

## EVALUATION
### Best Model Testing and Evaluation
```{r}
load(file="./data/fit_best.rda")
```
```{r}
predict_best = augment(fit_best, test)
```
```{r}
roc_auc(data=predict_best, truth=recovered_Y,
        estimate=.pred_1, event_level="second")
```
```{r}
accuracy(data=predict_best, truth=recovered_Y,
         estimate=.pred_class)
```
```{r}
conf_mtx = conf_mat(data=predict_best, truth=recovered_Y,
                    estimate=.pred_class)
conf_mtx$table
```
